import {
  Users,
  Building2,
  ThumbsUp,
  Clock,
  Star,
  Award,
  CheckCircle2,
  Shield,
  Heart,
  TrendingUp,
  MapPin,
  Briefcase,
  Calendar,
  Zap,
  Phone,
  type LucideIcon,
} from 'lucide-react'

export const STAT_ICON_MAP: Record<string, LucideIcon> = {
  Users,
  Building2,
  ThumbsUp,
  Clock,
  Star,
  Award,
  CheckCircle2,
  Shield,
  Heart,
  TrendingUp,
  MapPin,
  Briefcase,
  Calendar,
  Zap,
  Phone,
}

export const STAT_ICON_OPTIONS = [
  { value: 'Users', label: 'People / Users' },
  { value: 'Building2', label: 'Building / Facility' },
  { value: 'ThumbsUp', label: 'Thumbs Up' },
  { value: 'Clock', label: 'Clock / Time' },
  { value: 'Star', label: 'Star / Rating' },
  { value: 'Award', label: 'Award / Achievement' },
  { value: 'CheckCircle2', label: 'Check Circle / Quality' },
  { value: 'Shield', label: 'Shield / Trust' },
  { value: 'Heart', label: 'Heart / Care' },
  { value: 'TrendingUp', label: 'Growth / Trending' },
  { value: 'MapPin', label: 'Location / Pin' },
  { value: 'Briefcase', label: 'Briefcase / Jobs' },
  { value: 'Calendar', label: 'Calendar / Schedule' },
  { value: 'Zap', label: 'Zap / Fast' },
  { value: 'Phone', label: 'Phone / Contact' },
]
